name: "🐛 Bug Report"
description: "Signaler un bug ou un comportement inattendu"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug !

  - type: textarea
    id: description
    attributes:
      label: "Description du bug"
      description: "Décrivez clairement le problème rencontré"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Étapes pour reproduire"
      description: "Comment reproduire le bug ?"
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Comportement attendu"
      description: "Que devrait-il se passer ?"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "Quelle version utilisez-vous ?"
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Système d'exploitation"
      options:
        - Linux
        - macOS
        - Windows
        - Autre
    validations:
      required: true
